Gtl 166 front modal cambio de contraseña
GATLA-Meditations/GATLA-Frontend pull request #34
Opened 2024-06-01 19:13 UTC by AAugurusa

2024-06-02 19:21 UTC, maxigeist commented on src/components/ChangePassword/styles.css
> +    background: var(--primary-100, #e8e7fc);
acá le mandaría un bg-color quizás para que no queden los inputs en amarillo

2024-06-02 19:28 UTC, maxigeist requested changes

2024-06-02 19:28 UTC, maxigeist commented on src/components/ChangePassword/styles.css
> +    background: var(--primary-100, #e8e7fc);
Acá le mandaría un var(--bg-color) como para que no queden los inputs box amarillos

2024-06-02 19:28 UTC, maxigeist commented on src/components/ChangePassword/styles.css
> +    width: 372px;
el width y el height los pondría como porcentaje porque en algunas pantallas de teléfono queda enorme el modal

2024-06-02 19:28 UTC, maxigeist commented on src/pages/testpassmodal/index.tsx
No se si pushieria esto, ya se puede ver en el profile que funque

2024-06-02 20:03 UTC, AAugurusa commented on src/pages/testpassmodal/index.tsx
pense que lo habia borrado max, dale lo depreco y le mando el resto de las cosas

2024-06-04 23:43 UTC, SantiPe02 approved these changes

2024-06-04 23:44 UTC, SantiPe02 approved these changes

2024-06-04 23:44 UTC, maxigeist approved these changes

2024-06-04 23:44 UTC, merged