Gtl 177 front end pagina ver logros
GATLA-Meditations/GATLA-Frontend pull request #35
Opened 2024-06-02 16:18 UTC by AAugurusa

2024-06-02 19:38 UTC, maxigeist requested changes

2024-06-02 19:38 UTC, maxigeist commented on src/pages/achievements/index.tsx
> +        <Box height={'100vh'} style={{ backgroundColor: 'var(--bg-color)' }}>
creo que le sacaría el bg-color al background porque sino parece que las cards estan flotando y que la grilla no tiene fondo.

2024-06-02 21:48 UTC, AAugurusa commented on src/pages/achievements/index.tsx
> +        <Box height={'100vh'} style={{ backgroundColor: 'var(--bg-color)' }}>
Listo maxo

2024-06-04 23:42 UTC, maxigeist approved these changes
LGTM

2024-06-04 23:43 UTC, merged